// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuntosColombia.Web.Data;

namespace PuntosColombia.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PuntosColombia.Web.Data.Entities.MissingNumber", b =>
                {
                    b.Property<int>("MissingNumberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ListA");

                    b.Property<string>("ListB");

                    b.Property<string>("ListResult");

                    b.Property<int>("QuantityListA");

                    b.Property<int>("QuantityListB");

                    b.HasKey("MissingNumberId");

                    b.ToTable("MissingNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
